CREATE TABLE CLIENTE(
NUMERO_CONTA VARCHAR(20) NOT NULL,
NOME VARCHAR(50) NOT NULL,
DATA_NASCIMENTO DATE,
PLANO_EXCLUSIVE BOOLEAN,
SALDO NUMERIC(9,2),
CONSTRAINT PK_CLIENTE PRIMARY KEY(NUMERO_CONTA)
);

CREATE TABLE HISTORICO_MOVIMENTACAO_CONTA(
ID_MOVIMENTACAO INT NOT NULL,
TIPO_MOVIMENTACAO VARCHAR(50) NOT NULL,
DATA_MOVIMENTACAO DATE,
VALOR_MOVIMENTACAO NUMERIC(9,2),
VALOR_TAXA_ADMINISTRACAO NUMERIC,
REGRA_TAXA_APLICADA VARCHAR(50) NOT NULL,
SALDO_ANTERIOR NUMERIC(9,2),
SALDO_ATUAL NUMERIC(9,2),
NUMERO_CONTA VARCHAR(50) NOT NULL,
CONSTRAINT PK_HISTORICO_MOVIMENTACAO_CONTA PRIMARY KEY(ID_MOVIMENTACAO),
CONSTRAINT FK_CONTA_HISTORICO_MOVIMENTACAO_CONTA FOREIGN KEY(NUMERO_CONTA) REFERENCES CLIENTE(NUMERO_CONTA)
);
